<?php

namespace Grelu\SurveyJsBundle\Repository;

/**
 * DataSurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSurveyRepository extends \Doctrine\ORM\EntityRepository
{
}
